=== jriveraf01/TrabajoDiario/T5/Boletin5.1/Ej3.dtd
<!ELEMENT socios (socio)+>
<!ELEMENT socio (nombre,edad,numero,clave)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT clave (#PCDATA)>

=== jriveraf01/TrabajoDiario/T5/Boletin5.1/Ej3.xml
<!DOCTYPE socios SYSTEM "Ej3.dtd">

<socios>
  <socio>
    <nombre>Ana</nombre>
    <edad>21</edad>
  </socio>
  <socio>
    <numero>598</numero>
    <nombre>iker</nombre>
    <edad>19</edad>
  </socio>
  <socio>
    <clave>3rffwe</clave>
    <nombre>iker</nombre>
  </socio>
</socios>
